all:
	gcc -o dining_philosophers dining_philosophers.c -lpthread
	gcc -o training_monkey training_monkey.c -lpthread
	gcc -o mysyscall_test mysyscall_test.c 
clean:
	rm dining_philosophers training_monkey mysyscall_test
